name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Zip Deploy Package (no .env)
        run: |
          zip -r deploy.zip dist node_modules package.json prisma

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: graphql-test-mgr
          environment_name: Graphql-test-mgr-env
          region: ap-southeast-1
          version_label: ${{ github.run_id }}
          deployment_package: deploy.zip
